config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/show'
  devise_for :users
  root to: 'pages#home'


  resources :cars do
    resources :bookings, only: [:new, :create, :show]
  end
  resources :bookings, only: :destroy

  resources :dashboard, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :starts_at, presence: true
  validates :ends_at, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  include PgSearch
  mount_uploader :photo, PhotoUploader
  belongs_to :user_as_owner, class_name: "User", foreign_key: 'user_id'
  has_many :bookings
  has_many :users_as_renter, through: :bookings, source: :user

  pg_search_scope :full_text_search,
    against: [ :brand, :description],
    using: {
      tsearch: { prefix: true }
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :owned_cars, class_name: "Car"
  has_many :bookings
  has_many :booked_cars, through: :bookings, source: :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
    @car = Car.find(params[:car_id])
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id])
    @booking.car = @car
    @booking.user = current_user
     if @booking.save
      flash[:notice] = "Your booking has been placed"
      redirect_to car_booking_path(@car, @booking)
    else
      flash[:alert] = @booking.errors.full_messages
      render 'cars/show'
    end
  end


  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete
    redirect_to car_path(@booking.car)
  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at, :car_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = search_for_car(Car.all)
    # params[:query]
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user_as_owner = current_user
    if @car.save
      redirect_to dashboard_path(current_user)
    else
      flash[:alert] = @car.errors.full_messages
      render 'new'
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)

    redirect_to car_path(@car)
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:brand, :price, :description, :photo, :user_id)
  end

  def search_for_car(scope)
    if params[:query].present?
      Car.full_text_search(params[:query])
    else
      Car.all
    end
  end

  def further_surch
     if params[:query].present?
      sql_query = "brand ILIKE :query OR description ILIKE :query OR price ILIKE :query"
      @cars = Car.where(sql_query, query: "%#{params[:query]}%")
    else
      @cars = Car.all
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:user_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="banner_confirmation" style="background-image: linear-gradient(-150deg, rgba(0,101,168,0.6) 0%, rgba(0,0,0,0) 1%), url('<%= cl_image_path(@car.photo_url) if @car.photo_url.present? %>')">
  <div class="confirm_page_container">
    <div class="container">
      <div class="container-content">
        <div class="container-header">
          <h1>Almost done!</h1>
          <h3>Confirm your Infos</h3>
        </div>
        <div class="container-text">
          <p><strong><%= @car.brand %></strong></p>
          <p>Price: <%= @car.price %>€</p>
          <p><strong>From: </strong> <%= @booking.starts_at %><strong>   To: </strong><%= @booking.ends_at %></p>
          <p>Owner: <%= @car.user_as_owner.email %></p>
          <p>Paymentmethod: Mastercard</p>
          <div class="confrimation_buttons">
            <p><%= link_to "Confirm", dashboard_path %></button></p>
            <p><%= link_to "Cancel booking", booking_path(@booking), method: :delete  %></button></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cars/edit.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1523676060187-f55189a71f5e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ead3ae36f1c95df4cdb88434540e29ad&auto=format&fit=crop&w=1650&q=80');">
 <div class="banner-content">
   <div class="view_new">
     <div class="flexbox">
       <div class="page_new">
         <div style="text-align: center;">
           <h1>Update your Car</h1>
           <p>Please enter the car infos!</p>
           <div class="users_input">
             <%= simple_form_for @car do |f| %>
             <div class="input_field">
               <%= f.input :brand %>
               <%= f.input :price %>
               <%= f.input :description %>
               <%= f.input :photo %>
               <%= f.input :photo_cache, as: :hidden %>
               <%= f.submit "Update car", class: "btn btn-primary" %>
             </div>
             <% end %>
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/cars/index.html.erb
<div>
 <div>
   <div class="banner_index" style="background-image: linear-gradient(-150deg, rgba(0,101,168,0.6) 0%, rgba(0,0,0,0) 1%), url('<%= image_path "car3.jpg" %>'); background-position:  58% 60%">
 </div>



<% @cars.each do |car| %>
   <div class="outer_box">
     <div class="flexbox">
       <div class="grid">
         <div class="image">
          <p>
            <%= cl_image_tag car.photo_url, width: 262 if car.photo_url.present? %>
          </p>
         </div>
         <div class="information">
           <div class="price_brand">
             <h4 class="cars_brand classic_font" id="car_name"><b><%=car.brand%></b>
             <h4 class="classic_font"><b><%= car.price %> €</b></h4>
           </div>
           <p class="cars_description classic_font"style="text-align: center;"><%= %></p>
           <div class="symbols_and_buttom">
             <p class="buttom_information"><%= link_to "Book", car_path(car), id:"book_buttom",class: "btn btn-treehouse" %></p>
             <div class="symbols">
               <p class="fair_fuel"><i class="fas fa-gas-pump "></i>Fair refuel</p>
               <p class="insurance"><i class="fas fa-check"></i>Good insurance</p>
             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
<% end %>

app/views/cars/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "car1.jpg" %>');">

<div class="banner-content">
  <div class="view_new">
      <div class="page_new">
        <div style="text-align: center;" class="small_container">
          <h1 class="classic_font">Add your Car</h1>
          <p class="classic_font">Please enter the car infos!</p>
          <div class="users_input">
            <%= simple_form_for @car do |f| %>
            <div class="input_field">
              <%= f.input :brand %>
              <%= f.input :price %>
              <%= f.input :description %>
              <%= f.input :photo %>
             <p><%= f.input :photo_cache, as: :hidden %></p>
              <%= f.submit "Add car", class: "btn btn-primary", id:"knopf" %>
            </div>
            <% end %>
          </div>
        </div>

       </div>
  </div>
</div>
</div>

<div class="beneath_banner_flexbox">
 <div class="beneath_banner_flex">
  <div class="text_beneath_banner">
    <h3>AMAX Insurance</h3>
    <p>To make sure your car will be taken care of</p>
    <img src="" alt="">
  </div>
 </div>
</div>

<div class="beneath_banner_flexbox">
 <div class="beneath_banner_flex">
  <div class="text_beneath_banner">
    <h3>creating opertunities</h3>
    <p>giving others the opertunity to drive their dream</p>
    <img src="" alt="">
  </div>
 </div>
</div>

app/views/cars/show.html.erb
<br>
<br>
<br>
<div class="container">
   <div class="outer_grid_container">
     <div class="grid_container">
       <div class="main_container">
          <div class="container_left"
               style="background-image: linear-gradient(-150deg, rgba(0,101,168,0.6) 0%, rgba(0,0,0,0) 1%), url('<%= cl_image_path(@car.photo_url) if @car.photo_url.present? %>')"
          >
          </div>
            <div class="container_right_top1 classic_font">
              <h4><strong><%= @car.brand %></strong></h4>
            </div>
              <div class="container_right_top2 classic_font">
                <p id="car_price"><strong><%= @car.price %> € </strong></p>
                <p id="des"><%=@car.description%></p>
              </div>
                <div class="container_right_bottom">
                  <div class="symbols_and_buttom" id="symbole">
                      <p class="fair_fuel"><i class="fas fa-gas-pump "></i>Fair refuel</p>
                      <p class="insurance"><i class="fas fa-check"></i>Good insurance</p>
                  </div>

                  <div class="form-wrapper" >
                    <%= simple_form_for [@car, @booking] do |f| %>
                    <div class="form-group" id="date_form">
                       <%= f.input :starts_at, as: :date, html5: true %>
                       <%= f.input :ends_at, as: :date, html5: true %>
                      <%= f.submit class: 'btn btn-treehouse', id: "book_buttom" %>
                   <% end %>
                    </div>
                  </div>
              </div>
          </div>
    </div>
</div>

app/views/dashboard/show.html.erb
<h2 classic_font id="head">My booked cars</h2>

<% current_user.booked_cars.each do |car| %>
<div class="outer_box">
  <div class="flexbox">
    <div class="grid">
      <div class="image">
          <%= cl_image_tag car.photo_url, width: 262 if car.photo_url.present? %>
      </div>
          <div class="information classic_font">
            <div class="price_brand">
             <h4 class="cars_brand classic_font" id="car_name"><b><%=car.brand%></b>
             <h4 class="classic_font"><b><%= car.price %> €</b></h4>
            </div>
            <!--   <p><%= car.description %></p> -->
              <div class="infos">
                <p>From: <%= @booking.starts_at %></p>
                <p>To: <%= @booking.ends_at %></p>
                <h5>Owner: <%= car.user_as_owner.email %></h5>
              </div>
          </div>
    </div>
  </div>
</div>
<% end %>

<h2 classic_font id="head">My owned cars</h2>

<% current_user.owned_cars.each do |car| %>
<div class="outer_box">
  <div class="flexbox">
    <div class="grid">
      <div class="image">
          <%= cl_image_tag car.photo_url, width: 262 if car.photo_url.present? %>
      </div>
      <div class="information classic_font">
            <div class="price_brand">
              <h4 class="cars_brand classic_font" id="car_name">
              <b><%=car.brand%></b>
              <h4 class="classic_font"><b><%= car.price %> €</b></h4>
            </div>
              <div class="infos">
                <h5>Owner: <%= car.user_as_owner.email %></h5>
              </div>
            </div>
          </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Classic Cars</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    </div>
      <%= render "components/navbar" %>
    </div>
      <%= yield %>
    <div><%= render "components/footer" %></div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "car.jpg" %>');">
  <div class="banner-content">
    <h1 class="classic_font">Welcome to Classic <br> car rental</h1>
    <p class="classic_font">established 2018</p>
      <div class= "home id="search_bar"">
        <!-- Search form -->
        <div class="homepage_search ersten" id="search_bar">
          <%= form_tag cars_path, method: :get do %>
          <%= text_field_tag :query,params[:query], class: "fom-control ersten", placeholder: "Location"%>
            <%= text_field_tag :query,params[:query], class: "fom-control ersten", placeholder: "Car brand"%><input type="submit" id="search_submit_button"class="ersten search_button">
          <% end %>
        </div>
      </div>
  </div>
</div>
<div class="homepage_insurance_and_reason_divs">
  <div class="beneath_banner_flexbox">
   <div class="beneath_banner_flex">
    <div class="text_beneath_banner">
      <h3><b>AMAX Insurance</b></h3>
      <p>To make sure your car will be taken care of</p>
      <img src="" alt="">
    </div>
   </div>
  </div>
  <div class="beneath_banner_flexbox">
   <div class="beneath_banner_flex">
    <div class="text_beneath_banner">
      <h3><b>creating opertunities</b></h3>
      <p>giving others the opertunity to drive their dream</p>
      <img src="" alt="">
    </div>
   </div>
  </div>
</div>
<div class="homepage_bottom_grid">
  <div class="homepage_left_item">
    <h1 class="classic_font" style="text-align: center;"><b>Becoming a rolemodel</b></h1>
    <h3 class="classic_font"><b>rent your car</b></h3>
    <p class="classic_font" style="text-align: center;">Imaging others would enable you to have a ride in your <b>dream car</b>. <br> sign up now</p>
    <%= link_to 'Offer a car', new_car_path, class: "navbar-wagon-item navbar-wagon-link classic_font homepage_offer_button" %>

  </div>
  <div class="homepage_right_item">
    <div>
      <img class="homepage_grid_image"src="https://images.unsplash.com/photo-1508916615381-bf54b73c1382?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=3214a8580e059ee562c787a971cb52ac&auto=format&fit=crop&w=1650&q=80" alt="">
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>